### ISSUE TITLE
Roadmap to v1.0

### ISSUE THREAD

**Issue by Zarthus** [Zarthus/PHP-CLI-application#1]
- [ ] Properly detect command line arguments. 
  * `$this->command` should not rely to be the first parameter
  * Properly use `$this->args` to reflect all options specified
- [ ] Look for ways to remove the use of `parent::__construct()`, the less required content in your extension the better. 
- [ ] Look for better ways to improve setting of database credentials. The less places that have your password in plaintext in memory, the better.
- [ ] Add a method to print without newline
- [ ] Exit Code to string conversion
